### ISSUE TITLE
cmake error when compiling cholmod-extra

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [jluttine/cholmod-extra#2]
Hi Jaakko;

I get the following error when compiling cholmod-extra aftar "make"

In file included from Source/cholmod_spinv.c:42:0:
Include/cholmod_extra.h:45:34: fatal error: suitesparse/UFconfig.h: No such file or directory
 #include <suitesparse/UFconfig.h>
                                  ^
compilation terminated.
make: **\* [Build/cholmod_spinv.o] Error 1

I suspect that make can not find SuiteSparse UFconfig.h. This file can only be found in SuiteSparse versions older than 4.0.0. Would you please explain what changes I should make in order to compile the source with the most recent version of SuiteSparse?
For example, the file UFconfig.h (I think) is replaced by SuiteSpace_config.h, should I just replace the file?

Thanks

**Comment by jluttine** [comment]
Hi! It's been a while since I have used this package.. So yes, it depends on an old SuiteSparse version. As I haven't used this package nor SuiteSparse in a long time, I'm not sure what changes you would need to make. Also, I'm not sure when (if ever) I'd find time to take a look on this, sorry. Maybe some day... Of course, if you can find it out and make relevant changes as a pull request, that would be greatly appreciated. I wonder if this "sparse inverse" function has been implemented in some other maintained package you could use, I don't know.

**Comment by rwolst** [comment]
I've fixed this so that it will compile. Basically the config name has changed. Its also necessary to have the "cholmod_internal.h" file in the repo as this no longer gets installed when CHOLMOD is installed. I'll make a pull request.
